### ISSUE TITLE
Registry 0.9.1 is not able to mirror library/mysql:5.5

### ISSUE THREAD

**Issue by berndv** [docker/docker-registry#1012]
Since today, we end up with an error when pulling [mysql:5.5](https://registry.hub.docker.com/_/mysql/) via our private registry.
-   private reg is configured as mirror of https://registry-1.docker.io
-   tag is 0.9.1

Note: When pulling the image directly from registry-1.docker.io, the error also occurs with docker 1.5 **but not** with docker 1.6!

Error log on client side:

```
core@coreos ~ $ docker pull docker.bosch-si.com:5000/mysql:5.5
Pulling repository docker.bosch-si.com:5000/mysql
806951c10f4d: Error pulling image (5.5) from docker.bosch-si.com:5000/mysql, HTTP code 404
8ebbde154a62: Download complete
c12da83ee7c1: Download complete
a16207605ac6: Error pulling dependent layers
FATA[0019] Error pulling image (5.5) from docker.bosch-si.com:5000/mysql, HTTP code 404
```

From the registry log:

```
15/Jun/2015:08:42:41 +0000 DEBUG: args = {'image_id': u'a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757'}
15/Jun/2015:08:42:41 +0000 DEBUG: api_error: Image not found
15/Jun/2015:08:42:41 +0000 DEBUG: Source provided, registry acts as mirror
15/Jun/2015:08:42:41 +0000 DEBUG: Request: GET https://registry-1.docker.io/v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json
Headers: {'Accept-Encoding': u'gzip', 'Authorization': u'Token signature=1a6282cb325ff863dc8038f5688355f92eab29b1,repository="library/mysql",access=read', 'User-Agent': u'docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.16.0-30-generic os/linux arch/amd64'}
Args: ImmutableMultiDict([])
15/Jun/2015:08:42:41 +0000 INFO: Starting new HTTPS connection (1): registry-1.docker.io
15/Jun/2015:08:42:41 +0000 DEBUG: "GET /v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json HTTP/1.1" 400 49
15/Jun/2015:08:42:41 +0000 DEBUG: Source responded to request with non-200 status
15/Jun/2015:08:42:41 +0000 DEBUG: Response: 400
{"error": "Image is being uploaded, retry later"}

10.55.35.233 - - [15/Jun/2015:08:42:41 +0000] "GET /v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json HTTP/1.1" 404 28 "-" "docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.16.0-30-generic os/linux arch/amd64"
15/Jun/2015:08:42:42 +0000 DEBUG: args = {'image_id': u'a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757'}
15/Jun/2015:08:42:42 +0000 DEBUG: api_error: Image not found
15/Jun/2015:08:42:42 +0000 DEBUG: Source provided, registry acts as mirror
15/Jun/2015:08:42:42 +0000 DEBUG: Request: GET https://registry-1.docker.io/v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json
Headers: {'Accept-Encoding': u'gzip', 'Authorization': u'Token signature=1a6282cb325ff863dc8038f5688355f92eab29b1,repository="library/mysql",access=read', 'User-Agent': u'docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.16.0-30-generic os/linux arch/amd64'}
Args: ImmutableMultiDict([])
15/Jun/2015:08:42:42 +0000 INFO: Starting new HTTPS connection (1): registry-1.docker.io
15/Jun/2015:08:42:43 +0000 DEBUG: "GET /v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json HTTP/1.1" 400 49
15/Jun/2015:08:42:43 +0000 DEBUG: Source responded to request with non-200 status
15/Jun/2015:08:42:43 +0000 DEBUG: Response: 400
{"error": "Image is being uploaded, retry later"}

10.55.35.233 - - [15/Jun/2015:08:42:43 +0000] "GET /v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json HTTP/1.1" 404 28 "-" "docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.16.0-30-generic os/linux arch/amd64"
15/Jun/2015:08:42:44 +0000 DEBUG: args = {'image_id': u'a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757'}
15/Jun/2015:08:42:44 +0000 DEBUG: api_error: Image not found
15/Jun/2015:08:42:44 +0000 DEBUG: Source provided, registry acts as mirror
15/Jun/2015:08:42:44 +0000 DEBUG: Request: GET https://registry-1.docker.io/v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json
Headers: {'Accept-Encoding': u'gzip', 'Authorization': u'Token signature=1a6282cb325ff863dc8038f5688355f92eab29b1,repository="library/mysql",access=read', 'User-Agent': u'docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.16.0-30-generic os/linux arch/amd64'}
Args: ImmutableMultiDict([])
15/Jun/2015:08:42:44 +0000 INFO: Starting new HTTPS connection (1): registry-1.docker.io
15/Jun/2015:08:42:45 +0000 DEBUG: "GET /v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json HTTP/1.1" 400 49
15/Jun/2015:08:42:45 +0000 DEBUG: Source responded to request with non-200 status
15/Jun/2015:08:42:45 +0000 DEBUG: Response: 400
{"error": "Image is being uploaded, retry later"}

10.55.35.233 - - [15/Jun/2015:08:42:45 +0000] "GET /v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json HTTP/1.1" 404 28 "-" "docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.16.0-30-generic os/linux arch/amd64"
15/Jun/2015:08:42:46 +0000 DEBUG: args = {'image_id': u'a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757'}
15/Jun/2015:08:42:46 +0000 DEBUG: api_error: Image not found
15/Jun/2015:08:42:46 +0000 DEBUG: Source provided, registry acts as mirror
15/Jun/2015:08:42:46 +0000 DEBUG: Request: GET https://registry-1.docker.io/v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json
Headers: {'Accept-Encoding': u'gzip', 'Authorization': u'Token signature=1a6282cb325ff863dc8038f5688355f92eab29b1,repository="library/mysql",access=read', 'User-Agent': u'docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.16.0-30-generic os/linux arch/amd64'}
Args: ImmutableMultiDict([])
15/Jun/2015:08:42:46 +0000 INFO: Starting new HTTPS connection (1): registry-1.docker.io
15/Jun/2015:08:42:47 +0000 DEBUG: "GET /v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json HTTP/1.1" 400 49
15/Jun/2015:08:42:47 +0000 DEBUG: Source responded to request with non-200 status
15/Jun/2015:08:42:47 +0000 DEBUG: Response: 400
{"error": "Image is being uploaded, retry later"}

10.55.35.233 - - [15/Jun/2015:08:42:47 +0000] "GET /v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json HTTP/1.1" 404 28 "-" "docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.16.0-30-generic os/linux arch/amd64"
15/Jun/2015:08:42:49 +0000 DEBUG: args = {'image_id': u'a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757'}
15/Jun/2015:08:42:49 +0000 DEBUG: api_error: Image not found
15/Jun/2015:08:42:49 +0000 DEBUG: Source provided, registry acts as mirror
15/Jun/2015:08:42:49 +0000 DEBUG: Request: GET https://registry-1.docker.io/v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json
Headers: {'Accept-Encoding': u'gzip', 'Authorization': u'Token signature=1a6282cb325ff863dc8038f5688355f92eab29b1,repository="library/mysql",access=read', 'User-Agent': u'docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.16.0-30-generic os/linux arch/amd64'}
Args: ImmutableMultiDict([])
15/Jun/2015:08:42:49 +0000 INFO: Starting new HTTPS connection (1): registry-1.docker.io
15/Jun/2015:08:42:50 +0000 DEBUG: "GET /v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json HTTP/1.1" 400 49
15/Jun/2015:08:42:50 +0000 DEBUG: Source responded to request with non-200 status
15/Jun/2015:08:42:50 +0000 DEBUG: Response: 400
{"error": "Image is being uploaded, retry later"}

10.55.35.233 - - [15/Jun/2015:08:42:50 +0000] "GET /v1/images/a16207605ac67b9cf0ff3c9ff208d276a9e2020bfa545a80be9ddb9911104757/json HTTP/1.1" 404 28 "-" "docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.16.0-30-generic os/linux arch/amd64"
```

**Comment by dmp42** [comment]
Can you check?
I believe that was fixed on the hub side.

**Comment by minichate** [comment]
Still seeing this when pulling the `library/redis:2.8` image:

```
# ... snip
192.168.65.120 - - [06/Aug/2015:14:31:23 +0000] "GET /v1/images/cd896e1f93ccc82732fe365405cb686252356e36f2dac6f601dd7a5e85011f6e/json HTTP/1.1" 404 28 "-" "docker/1.6.0 go/go1.4.2 kernel/3.10.0-123.el7.x86_64 os/linux arch/amd64"
06/Aug/2015:14:31:24 +0000 DEBUG: args = {'image_id': u'cd896e1f93ccc82732fe365405cb686252356e36f2dac6f601dd7a5e85011f6e'}
06/Aug/2015:14:31:24 +0000 DEBUG: Auth Token = Token signature=ead278b9411895faf41e28a37d4cbb2c7c780854,repository="library/redis",access=read
06/Aug/2015:14:31:24 +0000 DEBUG: auth = {u'access': u'read', u'repository': u'library/redis', u'signature': u'ead278b9411895faf41e28a37d4cbb2c7c780854'}
06/Aug/2015:14:31:24 +0000 INFO: Starting new HTTPS connection (1): index.docker.io
06/Aug/2015:14:31:24 +0000 DEBUG: "GET /v1/repositories/library/redis/images HTTP/1.1" 200 None
06/Aug/2015:14:31:24 +0000 DEBUG: validate_token: Index returned 200
06/Aug/2015:14:31:24 +0000 DEBUG: api_error: Image not found
06/Aug/2015:14:31:24 +0000 DEBUG: Source provided, registry acts as mirror
06/Aug/2015:14:31:24 +0000 DEBUG: Request: GET https://registry-1.docker.io/v1/images/cd896e1f93ccc82732fe365405cb686252356e36f2dac6f601dd7a5e85011f6e/json
Headers: {'Accept-Encoding': u'gzip', 'X-Forwarded-Port': u'80', 'X-Forwarded-For': u'10.6.1.85', 'User-Agent': u'docker/1.6.0 go/go1.4.2 kernel/3.10.0-123.el7.x86_64 os/linux arch/amd64', 'Connection': u'keep-alive', 'X-Forwarded-Proto': u'http', 'Authorization': u'Token signature=ead278b9411895faf41e28a37d4cbb2c7c780854,repository="library/redis",access=read'}
Args: ImmutableMultiDict([])
06/Aug/2015:14:31:24 +0000 INFO: Starting new HTTPS connection (1): registry-1.docker.io
06/Aug/2015:14:31:25 +0000 DEBUG: "GET /v1/images/cd896e1f93ccc82732fe365405cb686252356e36f2dac6f601dd7a5e85011f6e/json HTTP/1.1" 400 49
06/Aug/2015:14:31:25 +0000 DEBUG: Source responded to request with non-200 status
06/Aug/2015:14:31:25 +0000 DEBUG: Response: 400
{"error": "Image is being uploaded, retry later"}

192.168.65.254 - - [06/Aug/2015:14:31:25 +0000] "GET /v1/images/cd896e1f93ccc82732fe365405cb686252356e36f2dac6f601dd7a5e85011f6e/json HTTP/1.1" 404 28 "-" "docker/1.6.0 go/go1.4.2 kernel/3.10.0-123.el7.x86_64 os/linux arch/amd64"
06/Aug/2015:14:31:26 +0000 DEBUG: args = {'image_id': u'cd896e1f93ccc82732fe365405cb686252356e36f2dac6f601dd7a5e85011f6e'}
06/Aug/2015:14:31:26 +0000 DEBUG: Auth Token = Token signature=ead278b9411895faf41e28a37d4cbb2c7c780854,repository="library/redis",access=read
06/Aug/2015:14:31:26 +0000 DEBUG: auth = {u'access': u'read', u'repository': u'library/redis', u'signature': u'ead278b9411895faf41e28a37d4cbb2c7c780854'}
06/Aug/2015:14:31:26 +0000 INFO: Starting new HTTPS connection (1): index.docker.io
06/Aug/2015:14:31:26 +0000 DEBUG: "GET /v1/repositories/library/redis/images HTTP/1.1" 200 None
06/Aug/2015:14:31:26 +0000 DEBUG: validate_token: Index returned 200
06/Aug/2015:14:31:26 +0000 DEBUG: api_error: Image not found
06/Aug/2015:14:31:26 +0000 DEBUG: Source provided, registry acts as mirror
06/Aug/2015:14:31:26 +0000 DEBUG: Request: GET https://registry-1.docker.io/v1/images/cd896e1f93ccc82732fe365405cb686252356e36f2dac6f601dd7a5e85011f6e/json
Headers: {'Accept-Encoding': u'gzip', 'X-Forwarded-Port': u'80', 'X-Forwarded-For': u'10.6.1.85', 'User-Agent': u'docker/1.6.0 go/go1.4.2 kernel/3.10.0-123.el7.x86_64 os/linux arch/amd64', 'Connection': u'keep-alive', 'X-Forwarded-Proto': u'http', 'Authorization': u'Token signature=ead278b9411895faf41e28a37d4cbb2c7c780854,repository="library/redis",access=read'}
Args: ImmutableMultiDict([])
06/Aug/2015:14:31:26 +0000 INFO: Starting new HTTPS connection (1): registry-1.docker.io
06/Aug/2015:14:31:26 +0000 DEBUG: "GET /v1/images/cd896e1f93ccc82732fe365405cb686252356e36f2dac6f601dd7a5e85011f6e/json HTTP/1.1" 400 49
06/Aug/2015:14:31:26 +0000 DEBUG: Source responded to request with non-200 status
06/Aug/2015:14:31:26 +0000 DEBUG: Response: 400
{"error": "Image is being uploaded, retry later"}

192.168.65.120 - - [06/Aug/2015:14:31:26 +0000] "GET /v1/images/cd896e1f93ccc82732fe365405cb686252356e36f2dac6f601dd7a5e85011f6e/json HTTP/1.1" 404 28 "-" "docker/1.6.0 go/go1.4.2 kernel/3.10.0-123.el7.x86_64 os/linux arch/amd64"
06/Aug/2015:14:31:28 +0000 DEBUG: args = {'image_id': u'cd896e1f93ccc82732fe365405cb686252356e36f2dac6f601dd7a5e85011f6e'}
06/Aug/2015:14:31:28 +0000 DEBUG: Auth Token = Token signature=ead278b9411895faf41e28a37d4cbb2c7c780854,repository="library/redis",access=read
06/Aug/2015:14:31:28 +0000 DEBUG: auth = {u'access': u'read', u'repository': u'library/redis', u'signature': u'ead278b9411895faf41e28a37d4cbb2c7c780854'}
06/Aug/2015:14:31:28 +0000 INFO: Starting new HTTPS connection (1): index.docker.io
06/Aug/2015:14:31:29 +0000 DEBUG: "GET /v1/repositories/library/redis/images HTTP/1.1" 200 None
06/Aug/2015:14:31:29 +0000 DEBUG: validate_token: Index returned 200
06/Aug/2015:14:31:29 +0000 DEBUG: api_error: Image not found
06/Aug/2015:14:31:29 +0000 DEBUG: Source provided, registry acts as mirror
06/Aug/2015:14:31:29 +0000 DEBUG: Request: GET https://registry-1.docker.io/v1/images/cd896e1f93ccc82732fe365405cb686252356e36f2dac6f601dd7a5e85011f6e/json
Headers: {'Accept-Encoding': u'gzip', 'X-Forwarded-Port': u'80', 'X-Forwarded-For': u'10.6.1.85', 'User-Agent': u'docker/1.6.0 go/go1.4.2 kernel/3.10.0-123.el7.x86_64 os/linux arch/amd64', 'Connection': u'keep-alive', 'X-Forwarded-Proto': u'http', 'Authorization': u'Token signature=ead278b9411895faf41e28a37d4cbb2c7c780854,repository="library/redis",access=read'}
Args: ImmutableMultiDict([])
06/Aug/2015:14:31:29 +0000 INFO: Starting new HTTPS connection (1): registry-1.docker.io
06/Aug/2015:14:31:29 +0000 DEBUG: "GET /v1/images/cd896e1f93ccc82732fe365405cb686252356e36f2dac6f601dd7a5e85011f6e/json HTTP/1.1" 400 49
06/Aug/2015:14:31:29 +0000 DEBUG: Source responded to request with non-200 status
06/Aug/2015:14:31:29 +0000 DEBUG: Response: 400
{"error": "Image is being uploaded, retry later"}
```

Let me know if there are any other details I can provide!

**Comment by marccampbell** [comment]
I'm seeing this issue with `redis:latest`, but only with the docker registry v1, it works with v2.  I don't think this is a client issue, what can we do to make this image pullable in v1 again?
