### ISSUE TITLE
Problem w S3 and multiple Gunicorn Workers

### ISSUE THREAD

**Issue by pmoosh** [docker/docker-registry#815]
Hi there,

I have an issue with the docker registry on S3 w/ a nginx proxy. Not quite sure where report it, as it might be boto related

I do a bunch of pushes - same image over and over again, until it finally hangs forever

I think it has to do with using multiple Gunicorn workers. This is what I diagnosed so far:

At the time it hangs I see the following in the registry logs:

172.17.0.4 - - [03/Dec/2014:22:13:14 +0000] "GET /v1/images/e004073beca0d74527ce0e0b42c8a58625626e098574deac759f0770b1dac6d4/json HTTP/1.0" 200 1442 "-" "docker/1.3.2 go/go1.3.2 git-commit/50b8feb kernel/3.17.2+ os/linux arch/amd64"

2014-12-03 22:13:14 [38] [INFO] Booting worker with pid: 38

2014-12-03 22:13:14 [1] [INFO] 4 workers

172.17.0.4 - - [03/Dec/2014:22:13:15 +0000] "GET /v1/images/1a8a08e616c057a09a3351c453fa76da82b27fcc6265f279055e6450eef5bba8/json HTTP/1.0" 200 1447 "-" "docker/1.3.2 go/go1.3.2 git-commit/50b8feb kernel/3.17.2+ os/linux arch/amd64"

172.17.0.4 - - [03/Dec/2014:22:13:15 +0000] "GET /v1/images/f662bcbc8a4468d541bdca3e5ef836cd5c924667366409775ac0fb68432d3ac1/json HTTP/1.0" 200 1479 "-" "docker/1.3.2 go/go1.3.2 git-commit/50b8feb kernel/3.17.2+ os/linux arch/amd64"

I did some comparision runs with ext4 and saw that although gunicorn restarts a workers, the push continues without any issues. Also when I limit the workers on S3 to just one, it also restarts the worker once in a while, but the push continues without a hitch. The problem occurs only with multiple (in my case 4) workers on S3.

How can I debug this further?

thanks

Peter

**Comment by dbason** [comment]
I'm running the docker image and on startup with s3(ceph) when it tries to create a new sqlalchemy database for search it runs into a bunch of locking errors and crashes.  I assume this is the threading issue mentioned, or should I create a new issue?

**Comment by pmoosh** [comment]
@dbason - that is a know issue: and the remedy is GUNICORN_OPTS=[--preload] ...
This is fixed in 0.9.1 or so.... out any day now. I have a container based on master from about 25 days ago here pmoosh/registry

**Comment by dmp42** [comment]
The last patch for 0.9.1 was pushed - will publish the release now - sorry for the delay.
I am closing this since it was fixed on master.

**Comment by clkao** [comment]
Is this in the current 0.9.1 image? I was still seeing similar issue where PUT choked.

**Comment by clkao** [comment]
With latest, after several push to the registry, push chokes with the following output:
```
172.17.42.1 - - [22/Jan/2015:07:54:54 +0000] "GET /v1/repositories/stdev/images HTTP/1.1" 200 6080 "-" "docker/1.4.1 go/go1.3.3 git
172.17.42.1 - - [22/Jan/2015:07:54:55 +0000] "GET /v1/repositories/library/stdev/tags HTTP/1.1" 200 1593 "-" "docker/1.4.1 go/go1.3
172.17.42.1 - - [22/Jan/2015:07:54:55 +0000] "GET /v1/images/0a6bcf2ee2656aba58ee80a6a425075b8e5fb416d09ce076a7f250337252ab1c/json
[2015-01-22 07:54:55 +0000] [40] [INFO] Autorestarting worker after current request.
172.17.42.1 - - [22/Jan/2015:07:54:55 +0000] "GET /v1/images/e2fdd382a6037f02ce2642a30b4f7a3e4530ef56fc7a4685d2085062445c523d/ances
172.17.42.1 - - [22/Jan/2015:07:54:55 +0000] "GET /v1/images/b61bc8bdcf32f7d76ab23ad2570a8e0fe1e48edb708553d55b081b500ea9a4a5/json
172.17.42.1 - - [22/Jan/2015:07:54:55 +0000] "GET /v1/images/8a171986abe91169cdf682052cf28eaafeacf1c94001fe0f94cf70dc75b82112/json
172.17.42.1 - - [22/Jan/2015:07:54:56 +0000] "GET /v1/images/f9cc1769dbf9a2ac8e15e1afa834e3c722558d3f8fefe890956cb17b497de71d/json
172.17.42.1 - - [22/Jan/2015:07:54:56 +0000] "GET /v1/images/07355d1df2f5e94c2bcedc9c6aaef4ef22e5ce3cce6b7845e19526c253f72b34/json
[2015-01-22 07:54:56 +0000] [40] [INFO] Worker exiting (pid: 40)
[2015-01-22 07:54:56 +0000] [57] [INFO] Booting worker with pid: 57
172.17.42.1 - - [22/Jan/2015:07:54:56 +0000] "GET /v1/images/ab3678b7f0ff390bcea1d5afbefc5b118c277b9b3352daf0014e0cedb2d0d426/json
172.17.42.1 - - [22/Jan/2015:07:54:57 +0000] "GET /v1/images/8575c685cfa3397a9829662437aa6fd58902dbd179ac947801224ab36867e8b4/json
172.17.42.1 - - [22/Jan/2015:07:54:57 +0000] "GET /v1/images/3bc745296aa6b4d2b729b5b39dab7467fca9887e802580e5a27cf92588c895de/json
```

the client hangs while starting to actually PUT new layer (note there's no PUT in the output for the registry yet):
```
Sending image list
Pushing repository localhost:5000/stdev (1 tags)
[...]
Image ab3678b7f0ff already pushed, skipping
Image 8575c685cfa3 already pushed, skipping
Image 3bc745296aa6 already pushed, skipping
```

**Comment by pmoosh** [comment]
@clkao are you using the -e GUNICORN_OPTS=[--preload] option?

**Comment by clkao** [comment]
@pmoosh yes, without [--preload] it wouldn't actually start at all!

**Comment by dmp42** [comment]
Heads-up:

 * --preload is causing issues (this is what this ticket is about)
 * 0.9.1 does not need --preload anymore

-> run the latest version, *without* --preload

Hope that helps.

**Comment by clkao** [comment]
@dmp42, this is the error when I run :latest without --preload: https://gist.github.com/clkao/ec742ffe9df2e9e2212d

**Comment by dmp42** [comment]
God I hate that code :-)

@clkao what happens if you start again *the same container* after the first failure?

**Comment by clkao** [comment]
somehow this now works on startup, even with a fresh image.
